### ISSUE TITLE
Use/reuse ISO strings

### ISSUE THREAD

**Issue by milotype** [WeblateOrg/language-data#245]
**Is your feature request related to a problem? If so, please describe.**

Weblate's _Language data_ component consists of 586 translatable strings! That is a lot of possibly unnecessary/different translations!

**Describe the solution you'd like**

Consider the automatic usage of original strings and translations from the Weblate project "iso-codes".

**Additional context**

I'm not a programmer and unfortunately can't help to implement such a _feature_, but IMO, this would reduce the amount of source code as well as of the translation work.

**Comment by nijel** [comment]
The merging logic is here:

https://github.com/WeblateOrg/language-data/blob/fe04bc8613ef2f1dcd2f9da13a8139fb0edbb5d9/Makefile#L39-L47

**Comment by milotype** [comment]
Please excuse, I'm not a programmer, so I don't understand the "merging logic", but I just see 586 strings which need to be translated for the component _Language data_ into different languages. They are not translated automaticaly. If they where, the component _Language data_ wouldn't be necessary at all ... 

Also, I do not undertand, how Weblate covers languages which are not defined in ISO languages (independant of being translated of not in the "iso-codes" project)??  If they where necessary, than you'd maybe have only a couple of languages in the _Language data_ component, but not 586 ...

**Comment by nijel** [comment]
I think we're discussing a non-existing problem. We do include translations from iso-codes where available. There might be a bug in the code, but to diagnose that, please show me a string which is not being used. The updates do not happen immediately as this triggered manually (typically when doing some other changes in our languages database).

The language data component is necessary as we have additional metadata for the languages which are not present in the iso-codes (for example plural definitions or text direction). We want to have the translations in a single place to be able to override them (and to have an overview how complete the translation is). 

One reason is that not in all language the translation is expected to be the same as in the iso-codes. For example, in Czech, iso-codes translates all the languages without a capital letter (because it's the general way how language names are written in Czech), but in Weblate the language name is always used as title and should be with a capital letter. Also, we diverge in how we write languages variants.

**Comment by milotype** [comment]
@nijel OK, thanks for explaining ... so I'm closing this issue if you don't mind.
