### ISSUE TITLE
Change from Sorani to central kurdish

### ISSUE THREAD

**Issue by cutiyar** [WeblateOrg/language-data#3]
Hey
The name of our language is central kurdish not Sorani and its a dialect of kurdish. we have Northern kurdish, southern kurdish and Central kurdish, Sorani and Kurmanji are two different standard script or writing script for them, they are not a language name.
You can see from here https://iso639-3.sil.org/code/ckb

Best Regards

**Comment by nijel** [comment]
Wikipedia describes that as if Sorani and Central Kurdish would be synomyms (https://en.wikipedia.org/wiki/Kurdish_languages#Subdivisions), but still it makes sense to be consistent with ISO here.

**Comment by cutiyar** [comment]
Thank you, now its ok.

**Comment by cutiyar** [comment]
Thank you, now its ok.

**Comment by jwtiyar** [comment]
Sorry Nijel
but why still sorani exist in some projects and central kurdish not available?
https://hosted.weblate.org/languages/ckb/

**Comment by comradekingu** [comment]
https://iso639-3.sil.org/code/ckb
This is Sorani in Hosted Weblate, but should be "Central Kurdish".
It is a bit of a discussion over at https://en.wikipedia.org/wiki/Talk:Sorani

https://translations.documentfoundation.org/languages/ckb/#overview has it right.

Are the different installation locales listed for each language selection listed anywhere?

Edit: If this is somehow disputed, "Central Sorani" seems like a middleground, because then at least people searching for "Central Kurdish", which I understand to be most people (?) will find it.

From what I can tell ckb should always be either ckb_IQ or ckb_IR ?

**Comment by nijel** [comment]
Fixed now. The upgrade script didn't update the language data, that's why it was not updated there.

**Comment by jwtiyar** [comment]
Thanks for great support, Now kurdish belongs to what? Northern and Central Kurdish are available you can change this Kurdish to southern kurdish, So we Cover all three one. And it will be great, without any confusion for kurdish people.

**Comment by nijel** [comment]
"Kurdish" is ku/kur and I believe it is correct. The question is whether using this makes sense, but that's not something we can control.

For Southern Kurdish there is https://hosted.weblate.org/languages/sdh/, though it's currently not used by any project there.

**Comment by jwtiyar** [comment]
I know its used by too much people, as i may mention before (when internet was new kurdish people ) we had just  kurdish which is three type sdh, kmr, ckb. these was not recognized by organizations. So it was mandatory to use kurdish even if you are translating in ckb, kmr, or sdh. this made the confusion , if you see the list for example OsmAnd ku is northern kurdish, then see newpipe its ckb.
This is the problem I am talking about.
If you need help i can tell you all projects in weblate which used ku, And you change the name from ku to what script they are translating, At the end you can see that we have distinguished them all. no more ku just ckb, kmr, or sdh.

Best Regards

**Comment by nijel** [comment]
This is not something to be addressed in Weblate - talk to these projects to use proper code for the language.

**Comment by CrowdsourceKurdish** [comment]
I know that Kurdish has dialects (kurmanji, sorani, xwarin), but I requested this because only "ku" can be used for kurmanji in projects. There were already two options for sorani-central.
Unicode does not accept IOS639-3, and unicode gives this;
ku_TR
Ku_IQ

ISO693-3;
Kmr: kurmanji/Northern
Ckb: sorani/central
![lang](https://user-images.githubusercontent.com/72891963/100342564-38b4e300-2fef-11eb-9dd9-9e0c148257f2.JPG)

**Comment by nijel** [comment]
We're discussing changing the naming of Kurdish variants; please share your feedback on https://github.com/WeblateOrg/language-data/pull/2386
